from tkinter import *
root=Tk()
l1=Label(root,text="Username")
e1=Entry(root)
l2=Label(root,text="Mobile Number")
e2=Entry(root)
l3=Label(root,text="Email id")
e3=Entry(root)
l4=Label(root,text="Age")
e4=Entry(root)
l5=Label(root,text="Password")
e5=Entry(root)
l6=Label(root,text="Confirm password")
e6=Entry(root)
but1=Button(root,text="Login")
but2=Button(root,text="Cancel")
l1.grid(row=0,column=0)
e1.grid(row=0,column=1)
l2.grid(row=1,column=0)
e2.grid(row=1,column=1)
l3.grid(row=2,column=0)
e3.grid(row=2,column=1)
l4.grid(row=3,column=0)
e4.grid(row=3,column=1)
l5.grid(row=4,column=0)
e5.grid(row=4,column=1)
l6.grid(row=5,column=0)
e6.grid(row=5,column=1)
but1.grid(row=6,column=1)
but2.grid(row=6,column=2)
root.mainloop()